[package]
name = "set1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1"
openssl = "0.10"

[dev-dependencies]
proptest = "1.0.0"
